### PR TITLE
Ignore renovate `eslint` updates

### PR DESCRIPTION
**Pull request by juliangruber**
https://github.com/juliangruber/isarray/pull/64#issuecomment-1272332785

### CODE REVIEW

**Comment by juliangruber** [comment]
@ljharb something seems off with automatic rebase 🤔

**Review by ljharb — APPROVED** [review]

**Comment by ljharb** [comment]
weird, `error: branch 'update/renovate-ignore-eslint' not found.` doesn't make any sense. i'll look into it, thanks

**Comment by juliangruber** [comment]
hmm weird, maybe a transient github issue

**Comment by juliangruber** [comment]
ok I see you had already rerun it. will merge 🙏

**Pull request merged**
