### PR TITLE
use Object.prototype.toString

### PR DESCRIPTION
**Pull request by nickleefly**

### CODE REVIEW

**Comment by mkoryak** [comment]
he might not want to do this because 
https://github.com/juliangruber/isarray/commit/1052c9d94dc87374cad15d7df017bfcccd8e3398

**Comment by juliangruber** [comment]
last time i checked this is slower. can you verify?

**Comment by nickleefly** [comment]
It is only slower on 5.9.1, the test is in [gist](https://gist.github.com/nickleefly/952915fca4b8304ecba9)
```
$ node -v
v5.8.0
$ node bench.js

Start isArray

  2 tests completed.
```

  isArray  x **36,544,463** ops/sec ±4.89% (238 runs sampled)
  isArray1 x **43,869,363** ops/sec ±4.31% (247 runs sampled)


```
$ node -v
v5.9.1
$ node bench.js

Start isArray

  2 tests completed.
```

  isArray  x **41,617,178** ops/sec ±4.59% (243 runs sampled)
  isArray1 x **40,984,845** ops/sec ±4.85% (273 runs sampled)

while

```
$ node -v
v4.4.1
$ node bench.js

Start isArray

  2 tests completed.
```

  isArray  x **44,621,606** ops/sec ±6.41% (264 runs sampled)
  isArray1 x **47,319,872** ops/sec ±2.79% (284 runs sampled)


and

```
$ node -v
v4.4.0
$ node bench.js

Start isArray
```

  2 tests completed.

  isArray  x **47,998,121** ops/sec ±1.16% (280 runs sampled)
  isArray1 x **48,294,691** ops/sec ±0.92% (285 runs sampled)

**Comment by nickleefly** [comment]
Ping @juliangruber

**Comment by Hyperion** [comment]
`Array.isArray ||` doesn't confuse you?

**Comment by juliangruber** [comment]
this is marginal, I don't think the slight perf improvement actually matters for any real world use case. closing this, it's just too tempting to optimize everything.

**Pull request closed without merging**
