### PR TITLE
More robust implementation

### PR DESCRIPTION
**Pull request by BlobTheKat**
Targets IE8+
(Browserify and webpack are not even compatible with IE7)

Targets any node version.

### CODE REVIEW

**Comment by Zekiah-A** [comment]
+1 for this PR, especially considering the performance improvement this library can see from not having to do the potentially costly (on some engines) string comparison to check for the array type, along with the static allocation of the '[object Array]' string literal. Also, ofc, the backwards compatibility with the code that was there before is good to ensure that anyone who depends on this doesn't suffer from any breakages

**Comment by BlobTheKat** [comment]
I am wondering if any optimizations could be made regarding inlining the .js file directly into the package.json. This could safe significantly more time in terms of synchronous waiting to read an extra file from disk and then parsed and instantiated.

**Comment by ljharb** [comment]
This is not actually more robust, specifically because it can be run in older browser engines - not just IE, but everything else.

You can easily alias out this module with `module.exports = Array.isArray` in your bundler, or even replace `require('isarray')` with `Array.isArray` directly - there is simply no meaningful benefit to end users that this package currently denies them - but making a change like this would deny others of a safe default.

JS can't be inlined into package.json, so i'm not really sure what you mean by that one.

**Comment by BlobTheKat** [comment]
> This is not actually more robust, specifically because it can be run in older browser engines - not just IE, but everything else.

I think you're missing the point from what I wrote in the comments I've written in index.js

This module _cannot_ run in old browsers since the ability to import npm modules altogether _does not_ target browsers that old (that is, neither babel, nor browserify, nor requirejs can actually use your package in its intended environment)

**Comment by ljharb** [comment]
I'm not sure what you mean. I often use an older version of browserify to target older browsers, and babel output works just fine in ancient browsers.

**Pull request closed without merging**
