### PR TITLE
Hypercomplicated fix to isArray.

### PR DESCRIPTION
**Pull request by PunchCakee**
Due to the sophisticated nature of this library i managed to thankfully speed this up by  294829348239048x

### CODE REVIEW

**Comment by juliangruber** [comment]
This will fail tests, as `typeof array === 'object'`

**Comment by ljharb** [comment]
every single troll attempt illustrates why this package is actually needed (－‸ლ)

**Comment by PunchCakee** [comment]
> every single troll attempt illustrates why this package is actually needed (－‸ლ)

more like how js devs are incompetent

**Comment by ljharb** [comment]
@PunchCakee that's an interesting claim since your own PR was incompetent.

**Comment by ljharb** [comment]
That doesn't sound to me like something a competent developer would do, even for a poor attempt at trolling.

**Pull request closed without merging**
